Namespace Access

  Public Class ExamCentreAssessmentType
    Inherits CARERecord
    Implements IRecordCreate

#Region "AutoGenerated Code"

'--------------------------------------------------
'Enum defining all the fields in the table
'--------------------------------------------------
    Private Enum ExamCentreAssessmentTypeFields
      AllFields = 0
      ExamCentreAssessmentTypeId
      ExamCentreId
      ExamAssessmentType
      CreatedBy
      CreatedOn
      AmendedBy
      AmendedOn
    End Enum

'--------------------------------------------------
'Required overrides for the class
'--------------------------------------------------
    Protected Overrides Sub AddFields()
      With mvClassFields
        .Add("exam_centre_assessment_type_id", CDBField.FieldTypes.cftInteger)
        .Add("exam_centre_id", CDBField.FieldTypes.cftInteger)
        .Add("exam_assessment_type")
        .Add("created_by")
        .Add("created_on", CDBField.FieldTypes.cftDate)

        .Item(ExamCentreAssessmentTypeFields.ExamCentreAssessmentTypeId).PrimaryKey = True
        .Item(ExamCentreAssessmentTypeFields.ExamCentreAssessmentTypeId).PrefixRequired = True
        .SetControlNumberField(ExamCentreAssessmentTypeFields.ExamCentreAssessmentTypeId, "XCT")

        .SetUniqueField(ExamCentreAssessmentTypeFields.ExamCentreId)
        .Item(ExamCentreAssessmentTypeFields.ExamAssessmentType).PrefixRequired = True
        .SetUniqueField(ExamCentreAssessmentTypeFields.ExamAssessmentType)
        .Item(ExamCentreAssessmentTypeFields.CreatedBy).PrefixRequired = True
        .Item(ExamCentreAssessmentTypeFields.CreatedOn).PrefixRequired = True
      End With
    End Sub

    Protected Overrides ReadOnly Property SupportsAmendedOnAndBy() As Boolean
      Get
        Return True
      End Get
    End Property
    Protected Overrides ReadOnly Property TableAlias() As String
      Get
        Return "ecat"
      End Get
    End Property
    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "exam_centre_assessment_types"
      End Get
    End Property

'--------------------------------------------------
'Default constructor
'--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub

'--------------------------------------------------
'IRecordCreate
'--------------------------------------------------
    Public Function CreateInstance(ByVal pEnv As CDBEnvironment) As CARERecord Implements IRecordCreate.CreateInstance
      Return New ExamCentreAssessmentType(mvEnv)
    End Function
'--------------------------------------------------
'Public property procedures
'--------------------------------------------------
    Public ReadOnly Property ExamCentreAssessmentTypeId() As Integer
      Get
        Return mvClassFields(ExamCentreAssessmentTypeFields.ExamCentreAssessmentTypeId).IntegerValue
      End Get
    End Property
    Public ReadOnly Property ExamCentreId() As Integer
      Get
        Return mvClassFields(ExamCentreAssessmentTypeFields.ExamCentreId).IntegerValue
      End Get
    End Property
    Public ReadOnly Property ExamAssessmentType() As String
      Get
        Return mvClassFields(ExamCentreAssessmentTypeFields.ExamAssessmentType).Value
      End Get
    End Property
    Public ReadOnly Property CreatedBy() As String
      Get
        Return mvClassFields(ExamCentreAssessmentTypeFields.CreatedBy).Value
      End Get
    End Property
    Public ReadOnly Property CreatedOn() As String
      Get
        Return mvClassFields(ExamCentreAssessmentTypeFields.CreatedOn).Value
      End Get
    End Property
    Public ReadOnly Property AmendedBy() As String
      Get
        Return mvClassFields(ExamCentreAssessmentTypeFields.AmendedBy).Value
      End Get
    End Property
    Public ReadOnly Property AmendedOn() As String
      Get
        Return mvClassFields(ExamCentreAssessmentTypeFields.AmendedOn).Value
      End Get
    End Property
#End Region


#Region "Non AutoGeneratedCode"

    Protected Overrides Sub PostValidateUpdateParameters(ByVal pParameterList As CDBParameters)
      MyBase.PostValidateUpdateParameters(pParameterList)
      If mvClassFields("exam_assessment_type").ValueChanged Then
        mvClassFields.CheckRecordExists(mvEnv)
      End If
    End Sub
#End Region
  End Class
End Namespace
