Namespace Access

  Public Class ExamExemptionUnit
    Inherits CARERecord
    Implements IRecordCreate

#Region "AutoGenerated Code"

'--------------------------------------------------
'Enum defining all the fields in the table
'--------------------------------------------------
    Private Enum ExamExemptionUnitFields
      AllFields = 0
      ExamExemptionUnitId
      ExamUnitId
      ExamExemptionId
      CreatedBy
      CreatedOn
      AmendedBy
      AmendedOn
    End Enum

'--------------------------------------------------
'Required overrides for the class
'--------------------------------------------------
    Protected Overrides Sub AddFields()
      With mvClassFields
        .Add("exam_exemption_unit_id", CDBField.FieldTypes.cftInteger)
        .Add("exam_unit_id", CDBField.FieldTypes.cftInteger)
        .Add("exam_exemption_id", CDBField.FieldTypes.cftInteger)
        .Add("created_by")
        .Add("created_on", CDBField.FieldTypes.cftDate)

        .Item(ExamExemptionUnitFields.ExamExemptionUnitId).PrimaryKey = True
        .Item(ExamExemptionUnitFields.ExamExemptionUnitId).PrefixRequired = True
        .SetControlNumberField(ExamExemptionUnitFields.ExamExemptionUnitId, "XEU")

        .SetUniqueField(ExamExemptionUnitFields.ExamUnitId)
        .SetUniqueField(ExamExemptionUnitFields.ExamExemptionId)
        .Item(ExamExemptionUnitFields.CreatedBy).PrefixRequired = True
        .Item(ExamExemptionUnitFields.CreatedOn).PrefixRequired = True
      End With
    End Sub

    Protected Overrides ReadOnly Property SupportsAmendedOnAndBy() As Boolean
      Get
        Return True
      End Get
    End Property
    Protected Overrides ReadOnly Property TableAlias() As String
      Get
        Return "eeu"
      End Get
    End Property
    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "exam_exemption_units"
      End Get
    End Property

'--------------------------------------------------
'Default constructor
'--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub

'--------------------------------------------------
'IRecordCreate
'--------------------------------------------------
    Public Function CreateInstance(ByVal pEnv As CDBEnvironment) As CARERecord Implements IRecordCreate.CreateInstance
      Return New ExamExemptionUnit(mvEnv)
    End Function
'--------------------------------------------------
'Public property procedures
'--------------------------------------------------
    Public ReadOnly Property ExamExemptionUnitId() As Integer
      Get
        Return mvClassFields(ExamExemptionUnitFields.ExamExemptionUnitId).IntegerValue
      End Get
    End Property
    Public ReadOnly Property ExamUnitId() As Integer
      Get
        Return mvClassFields(ExamExemptionUnitFields.ExamUnitId).IntegerValue
      End Get
    End Property
    Public ReadOnly Property ExamExemptionId() As Integer
      Get
        Return mvClassFields(ExamExemptionUnitFields.ExamExemptionId).IntegerValue
      End Get
    End Property
    Public ReadOnly Property CreatedBy() As String
      Get
        Return mvClassFields(ExamExemptionUnitFields.CreatedBy).Value
      End Get
    End Property
    Public ReadOnly Property CreatedOn() As String
      Get
        Return mvClassFields(ExamExemptionUnitFields.CreatedOn).Value
      End Get
    End Property
    Public ReadOnly Property AmendedBy() As String
      Get
        Return mvClassFields(ExamExemptionUnitFields.AmendedBy).Value
      End Get
    End Property
    Public ReadOnly Property AmendedOn() As String
      Get
        Return mvClassFields(ExamExemptionUnitFields.AmendedOn).Value
      End Get
    End Property
#End Region

  End Class
End Namespace
