Namespace Access
  Public Class ExamCandidateCategory
    Inherits ContactCategory
    Implements IRecordCreate

    '--------------------------------------------------
    'Required overrides for the class
    '--------------------------------------------------
    Protected Overrides Sub AddFields()
      mvClassFields.Add("exam_candidate_activity_id", CDBField.FieldTypes.cftInteger).PrimaryKey = True
      mvClassFields.Add("exam_booking_unit_id", CDBField.FieldTypes.cftLong)
      MyBase.AddFields()
      mvClassFields.RemoveAt(2)   'Remove contact_category_number
      mvClassFields.RemoveAt(2)   'Remove contact_number
      mvClassFields.SetControlNumberField(ContactCategoryFields.ContactCategoryNumber, "XCG")
    End Sub

    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "exam_candidate_activities"
      End Get
    End Property

    '--------------------------------------------------
    'Default constructor
    '--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub
    '--------------------------------------------------
    'IRecordCreate
    '--------------------------------------------------
    Public Function CreateInstance(ByVal pEnv As CDBEnvironment) As CARERecord Implements IRecordCreate.CreateInstance
      Return New ExamCandidateCategory(mvEnv)
    End Function
    '--------------------------------------------------
    'Public property procedures
    '--------------------------------------------------

#Region "Non-AutoGenerated Code"

    Protected Overrides Sub SetValid()
      MyBase.SetValid()

      If mvExisting = True AndAlso Me.IsValidForUpdate() = False Then
        RaiseError(DataAccessErrors.daeActivityAlreadyExistsInTimePeriod)
      End If
    End Sub
#End Region
  End Class

End Namespace
