Namespace Access

  Public Class StatusHistory
    Inherits CARERecord

#Region "AutoGenerated Code"

'--------------------------------------------------
'Enum defining all the fields in the table
'--------------------------------------------------
    Private Enum StatusHistoryFields
      AllFields = 0
      ContactNumber
      Status
      StatusReason
      ValidTo
      ResponseChannel
      AmendedBy
      AmendedOn
    End Enum

'--------------------------------------------------
'Required overrides for the class
'--------------------------------------------------
    Protected Overrides Sub AddFields()
      With mvClassFields
        .Add("contact_number", CDBField.FieldTypes.cftLong)
        .Add("status")
        .Add("status_reason", CDBField.FieldTypes.cftMemo)
        .Add("valid_to", CDBField.FieldTypes.cftDate)
        .Add("response_channel")

        .Item(StatusHistoryFields.ResponseChannel).InDatabase = mvEnv.GetDataStructureInfo(CDBEnvironment.cdbDataStructureConstants.cdbResponseChannel)
      End With
    End Sub

    Protected Overrides ReadOnly Property SupportsAmendedOnAndBy() As Boolean
      Get
        Return True
      End Get
    End Property
    Protected Overrides ReadOnly Property TableAlias() As String
      Get
        Return "sh"
      End Get
    End Property
    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "status_history"
      End Get
    End Property

'--------------------------------------------------
'Default constructor
'--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub

'--------------------------------------------------
'Public property procedures
'--------------------------------------------------
    Public ReadOnly Property ContactNumber() As Integer
      Get
        Return mvClassFields(StatusHistoryFields.ContactNumber).IntegerValue
      End Get
    End Property
    Public ReadOnly Property Status() As String
      Get
        Return mvClassFields(StatusHistoryFields.Status).Value
      End Get
    End Property
    Public ReadOnly Property StatusReason() As String
      Get
        Return mvClassFields(StatusHistoryFields.StatusReason).Value
      End Get
    End Property
    Public ReadOnly Property ValidTo() As String
      Get
        Return mvClassFields(StatusHistoryFields.ValidTo).Value
      End Get
    End Property
    Public ReadOnly Property ResponseChannel() As String
      Get
        Return mvClassFields(StatusHistoryFields.ResponseChannel).Value
      End Get
    End Property
    Public ReadOnly Property AmendedBy() As String
      Get
        Return mvClassFields(StatusHistoryFields.AmendedBy).Value
      End Get
    End Property
    Public ReadOnly Property AmendedOn() As String
      Get
        Return mvClassFields(StatusHistoryFields.AmendedOn).Value
      End Get
    End Property
#End Region

  End Class
End Namespace
