Namespace Access

  Public Class EmailQueueItem
    Inherits CARERecord

#Region "AutoGenerated Code"

'--------------------------------------------------
'Enum defining all the fields in the table
'--------------------------------------------------
    Private Enum EmailQueueFields
      AllFields = 0
      EmailJobNumber
      EmailItemNumber
      ContactNumber
      EMailAddress
      MergeData
      ProcessedOn
      ProcessedStatus
      ErrorNumber
    End Enum

'--------------------------------------------------
'Required overrides for the class
'--------------------------------------------------
    Protected Overrides Sub AddFields()
      With mvClassFields
        .Add("email_job_number", CDBField.FieldTypes.cftLong)
        .Add("email_item_number", CDBField.FieldTypes.cftLong)
        .Add("contact_number", CDBField.FieldTypes.cftLong)
        .Add("email_address")
        .Add("merge_data", CDBField.FieldTypes.cftMemo)
        .Add("processed_on", CDBField.FieldTypes.cftTime)
        .Add("processed_status")
        .Add("error_number", CDBField.FieldTypes.cftLong)

        .Item(EmailQueueFields.EmailJobNumber).PrimaryKey = True
        .Item(EmailQueueFields.EmailItemNumber).PrimaryKey = True
        .Item(EmailQueueFields.ProcessedStatus).PrimaryKey = True
      End With
    End Sub

    Protected Overrides ReadOnly Property SupportsAmendedOnAndBy() As Boolean
      Get
        Return False
      End Get
    End Property
    Protected Overrides ReadOnly Property TableAlias() As String
      Get
        Return "eq"
      End Get
    End Property
    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "email_queue"
      End Get
    End Property

'--------------------------------------------------
'Default constructor
'--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub

'--------------------------------------------------
'Public property procedures
'--------------------------------------------------
    Public ReadOnly Property EmailJobNumber() As Integer
      Get
        Return mvClassFields(EmailQueueFields.EmailJobNumber).IntegerValue
      End Get
    End Property
    Public ReadOnly Property EmailItemNumber() As Integer
      Get
        Return mvClassFields(EmailQueueFields.EmailItemNumber).IntegerValue
      End Get
    End Property
    Public ReadOnly Property ContactNumber() As Integer
      Get
        Return mvClassFields(EmailQueueFields.ContactNumber).IntegerValue
      End Get
    End Property
    Public ReadOnly Property EmailAddress() As String
      Get
        Return mvClassFields(EmailQueueFields.EMailAddress).Value
      End Get
    End Property
    Public ReadOnly Property MergeData() As String
      Get
        Return mvClassFields(EmailQueueFields.MergeData).Value
      End Get
    End Property
    Public ReadOnly Property ProcessedOn() As String
      Get
        Return mvClassFields(EmailQueueFields.ProcessedOn).Value
      End Get
    End Property
    Public ReadOnly Property ProcessedStatus() As String
      Get
        Return mvClassFields(EmailQueueFields.ProcessedStatus).Value
      End Get
    End Property
    Public ReadOnly Property ErrorNumber() As Integer
      Get
        Return mvClassFields(EmailQueueFields.ErrorNumber).IntegerValue
      End Get
    End Property
#End Region

#Region "Non AutoGenerated Code"

    Protected Overrides Sub SetDefaults()
      MyBase.SetDefaults()
      mvClassFields(EmailQueueFields.ProcessedStatus).Value = "U"
    End Sub

    Public Sub SetProcessing()
      mvClassFields(EmailQueueFields.ProcessedOn).Value = TodaysDateAndTime()
      mvClassFields(EmailQueueFields.ProcessedStatus).Value = "P"
    End Sub

    Public Sub SetProcessed()
      mvClassFields(EmailQueueFields.ProcessedOn).Value = TodaysDateAndTime()
      mvClassFields(EmailQueueFields.ProcessedStatus).Value = "S"
      mvClassFields(EmailQueueFields.ErrorNumber).IntegerValue = 0
    End Sub

    Public Sub SetFailed(ByVal pErrorNumber As Integer)
      mvClassFields(EmailQueueFields.ProcessedOn).Value = TodaysDateAndTime()
      mvClassFields(EmailQueueFields.ProcessedStatus).Value = "F"
      mvClassFields(EmailQueueFields.ErrorNumber).IntegerValue = pErrorNumber
    End Sub

    Public Function ItemsToBeProcessedFields(ByVal pEmailJobNumber As Integer) As CDBFields
      CheckClassFields()
      Dim vWhereFields As New CDBFields()
      vWhereFields.Add(mvClassFields(EmailQueueFields.EmailJobNumber).Name, pEmailJobNumber)
      vWhereFields.Add(mvClassFields(EmailQueueFields.ProcessedStatus).Name, "U")
      vWhereFields.Add(mvClassFields(EmailQueueFields.ProcessedOn).Name)
      Return vWhereFields
    End Function

#End Region

  End Class
End Namespace
