Namespace Access

  Public Class ContactGroupUser
    Inherits CARERecord

#Region "AutoGenerated Code"

    '--------------------------------------------------
    'Enum defining all the fields in the table
    '--------------------------------------------------
    Public Enum ContactGroupUserFields
      AllFields = 0
      ContactGroup
      Department
      AmendedBy
      AmendedOn
    End Enum

    '--------------------------------------------------
    'Required overrides for the class
    '--------------------------------------------------
    Protected Overrides Sub AddFields()
      With mvClassFields
        .Add("contact_group")
        .Add("department")

        .Item(ContactGroupUserFields.ContactGroup).PrimaryKey = True
        .Item(ContactGroupUserFields.ContactGroup).PrefixRequired = True

        .Item(ContactGroupUserFields.ContactGroup).PrefixRequired = True

        .Item(ContactGroupUserFields.Department).PrimaryKey = True
        .Item(ContactGroupUserFields.Department).PrefixRequired = True

        .Item(ContactGroupUserFields.Department).PrefixRequired = True
      End With
    End Sub

    Protected Overrides ReadOnly Property SupportsAmendedOnAndBy() As Boolean
      Get
        Return True
      End Get
    End Property
    Protected Overrides ReadOnly Property TableAlias() As String
      Get
        Return "cgu"
      End Get
    End Property
    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "contact_group_users"
      End Get
    End Property

'--------------------------------------------------
'Default constructor
'--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub

'--------------------------------------------------
'Public property procedures
'--------------------------------------------------
    Public Property ContactGroup() As String
      Get
        Return mvClassFields(ContactGroupUserFields.ContactGroup).Value
      End Get
      Set(value As String)
        mvClassFields(ContactGroupUserFields.ContactGroup).Value = value
      End Set
    End Property
    Public Property Department() As String
      Get
        Return mvClassFields(ContactGroupUserFields.Department).Value
      End Get
      Set(value As String)
        mvClassFields(ContactGroupUserFields.Department).Value = value
      End Set
    End Property
    Public Property AmendedBy() As String
      Get
        Return mvClassFields(ContactGroupUserFields.AmendedBy).Value
      End Get
      Set(value As String)
        mvClassFields(ContactGroupUserFields.AmendedBy).Value = value
      End Set
    End Property
    Public Property AmendedOn() As String
      Get
        Return mvClassFields(ContactGroupUserFields.AmendedOn).Value
      End Get
      Set(value As String)
        mvClassFields(ContactGroupUserFields.AmendedOn).Value = value
      End Set
    End Property
#End Region

    Public Sub New(ByVal pEnv As CDBEnvironment,
                   ByVal pContactGroup As String,
                   ByVal pDepartment As String)
      MyBase.New(pEnv)
      Me.CheckClassFields()
      Me.ContactGroup = pContactGroup
      Me.Department = pDepartment
    End Sub

    Public Sub New(ByVal pEnv As CDBEnvironment,
                   ByVal pContactGroup As ContactGroup,
                   ByVal pUser As CDBUser)
      Me.New(pEnv,
             pContactGroup.EntityGroupCode,
             pUser.Department)
    End Sub

  End Class
End Namespace
