Namespace Access

  Public Class WorkstreamLink
    Inherits CARERecord
    Implements IRecordCreate

#Region "AutoGenerated Code"

    '--------------------------------------------------
    'Enum defining all the fields in the table
    '--------------------------------------------------
    Private Enum WorkstreamLinkFields
      AllFields = 0
      WorkstreamLinkId
      WorkstreamId
      ExamBookingUnitId
      ExamScheduleId
      AmendedBy
      AmendedOn
    End Enum

    '--------------------------------------------------
    'Required overrides for the class
    '--------------------------------------------------
    Protected Overrides Sub AddFields()
      mvClassFields.Add("workstream_link_id", CDBField.FieldTypes.cftInteger)
      mvClassFields.Add("workstream_id", CDBField.FieldTypes.cftInteger)
      mvClassFields.Add("exam_booking_unit_id", CDBField.FieldTypes.cftInteger)
      mvClassFields.Add("exam_schedule_id", CDBField.FieldTypes.cftInteger)
      mvClassFields.SetControlNumberField(WorkstreamLinkFields.WorkstreamLinkId, "WL")
      mvClassFields(WorkstreamLinkFields.WorkstreamLinkId).PrimaryKey = True
      mvClassFields(WorkstreamLinkFields.WorkstreamLinkId).PrefixRequired = True
      mvClassFields(WorkstreamLinkFields.WorkstreamId).PrefixRequired = True
      mvClassFields(WorkstreamLinkFields.ExamBookingUnitId).PrefixRequired = True
      mvClassFields(WorkstreamLinkFields.ExamScheduleId).PrefixRequired = True
    End Sub

    Protected Overrides ReadOnly Property SupportsAmendedOnAndBy() As Boolean
      Get
        Return True
      End Get
    End Property
    Protected Overrides ReadOnly Property TableAlias() As String
      Get
        Return "wl"
      End Get
    End Property
    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "workstream_links"
      End Get
    End Property

    '--------------------------------------------------
    'Default constructor
    '--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub

    '--------------------------------------------------
    'IRecordCreate
    '--------------------------------------------------
    Public Function CreateInstance(ByVal pEnv As CDBEnvironment) As CARERecord Implements IRecordCreate.CreateInstance
      Return New ExamUnitLink(mvEnv)
    End Function
    '--------------------------------------------------
    'Public property procedures
    '--------------------------------------------------
    Public ReadOnly Property WorkstreamLinkId() As Integer
      Get
        Return mvClassFields(WorkstreamLinkFields.WorkstreamLinkId).IntegerValue
      End Get
    End Property
    Public Property WorkstreamId() As Integer
      Get
        Return mvClassFields(WorkstreamLinkFields.WorkstreamId).IntegerValue
      End Get
      Private Set(value As Integer)
        mvClassFields(WorkstreamLinkFields.WorkstreamId).IntegerValue = value
      End Set
    End Property
    Public Property ExamBookingUnitId() As Integer
      Get
        Return mvClassFields(WorkstreamLinkFields.ExamBookingUnitId).IntegerValue
      End Get
      Private Set(value As Integer)
        mvClassFields(WorkstreamLinkFields.ExamBookingUnitId).IntegerValue = value
      End Set
    End Property
    Public Property ExamScheduleId() As Integer
      Get
        Return mvClassFields(WorkstreamLinkFields.ExamScheduleId).IntegerValue
      End Get
      Private Set(value As Integer)
        mvClassFields(WorkstreamLinkFields.ExamScheduleId).IntegerValue = value
      End Set
    End Property
#End Region

    Public Shared Function GetOrCreateinstance(pEnv As CDBEnvironment, pWorkstream As Workstream, pExamBookingUnit As ExamBookingUnit) As WorkstreamLink
      If Not pWorkstream.Existing Then
        Throw New InvalidOperationException("Items can only be linked to existing workstreams.")
      End If
      If Not pExamBookingUnit.Existing Then
        Throw New InvalidOperationException("Only existing exam booking units can be linked to workstreams.")
      End If
      Dim vResult As New WorkstreamLink(pEnv)
      vResult.InitWithPrimaryKey(New CDBFields({New CDBField("workstream_id", pWorkstream.WorkstreamId),
                                                New CDBField("exam_booking_unit_id", pExamBookingUnit.ExamBookingUnitId)}))
      If Not vResult.Existing Then
        vResult.WorkstreamId = pWorkstream.WorkstreamId
        vResult.ExamBookingUnitId = pExamBookingUnit.ExamBookingUnitId
      End If
      Return vResult
    End Function

    Public Shared Function GetOrCreateinstance(pEnv As CDBEnvironment, pWorkstream As Workstream, pExamSchedule As ExamSchedule) As WorkstreamLink
      If Not pWorkstream.Existing Then
        Throw New InvalidOperationException("Items can only be linked to existing workstreams.")
      End If
      If Not pExamSchedule.Existing Then
        Throw New InvalidOperationException("Only existing exam schedules can be linked to workstreams.")
      End If
      Dim vResult As New WorkstreamLink(pEnv)
      vResult.InitWithPrimaryKey(New CDBFields({New CDBField("workstream_id", pWorkstream.WorkstreamId),
                                                New CDBField("exam_schedule_id", pExamSchedule.ExamScheduleId)}))
      If Not vResult.Existing Then
        vResult.WorkstreamId = pWorkstream.WorkstreamId
        vResult.ExamScheduleId = pExamSchedule.ExamScheduleId
      End If
      Return vResult
    End Function
  End Class
End Namespace
