Namespace Access

  Public Class PurchaseOrderType
    Inherits CARERecord

#Region "AutoGenerated Code"

'--------------------------------------------------
'Enum defining all the fields in the table
'--------------------------------------------------
    Private Enum PurchaseOrderTypeFields
      AllFields = 0
      PurchaseOrderType
      PurchaseOrderTypeDesc
      PaymentSchedule
      AdHocPayments
      RequiresAuthorisation
      RegularPayments
      RequiresPoPaymentType
      AmendedBy
      AmendedOn
    End Enum

'--------------------------------------------------
'Required overrides for the class
'--------------------------------------------------
    Protected Overrides Sub AddFields()
      With mvClassFields
        .Add("purchase_order_type")
        .Add("purchase_order_type_desc")
        .Add("payment_schedule")
        .Add("ad_hoc_payments")
        .Add("requires_authorisation")
        .Add("regular_payments")
        .Add("requires_po_payment_type")

        .Item(PurchaseOrderTypeFields.PurchaseOrderType).PrimaryKey = True

        .Item(PurchaseOrderTypeFields.AdHocPayments).InDatabase = mvEnv.GetDataStructureInfo(CDBEnvironment.cdbDataStructureConstants.cdbAdHocPurchaseOrderPayments)
        .Item(PurchaseOrderTypeFields.RequiresAuthorisation).InDatabase = mvEnv.GetDataStructureInfo(CDBEnvironment.cdbDataStructureConstants.cdbPurchaseOrderAuthorisation)
        .Item(PurchaseOrderTypeFields.RegularPayments).InDatabase = mvEnv.GetDataStructureInfo(CDBEnvironment.cdbDataStructureConstants.cdbRegularPurchaseOrderPayments)
        .Item(PurchaseOrderTypeFields.RequiresPoPaymentType).InDatabase = mvEnv.GetDataStructureInfo(CDBEnvironment.cdbDataStructureConstants.cdbRequiresPoPaymentType)
      End With
    End Sub

    Protected Overrides ReadOnly Property SupportsAmendedOnAndBy() As Boolean
      Get
        Return True
      End Get
    End Property
    Protected Overrides ReadOnly Property TableAlias() As String
      Get
        Return "pot"
      End Get
    End Property
    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "purchase_order_types"
      End Get
    End Property

'--------------------------------------------------
'Default constructor
'--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub

'--------------------------------------------------
'Public property procedures
'--------------------------------------------------
    Public ReadOnly Property PurchaseOrderTypeCode() As String
      Get
        Return mvClassFields(PurchaseOrderTypeFields.PurchaseOrderType).Value
      End Get
    End Property
    Public ReadOnly Property PurchaseOrderTypeDesc() As String
      Get
        Return mvClassFields(PurchaseOrderTypeFields.PurchaseOrderTypeDesc).Value
      End Get
    End Property
    Public ReadOnly Property PaymentSchedule() As Boolean
      Get
        Return mvClassFields(PurchaseOrderTypeFields.PaymentSchedule).Bool
      End Get
    End Property
    Public ReadOnly Property AmendedBy() As String
      Get
        Return mvClassFields(PurchaseOrderTypeFields.AmendedBy).Value
      End Get
    End Property
    Public ReadOnly Property AmendedOn() As String
      Get
        Return mvClassFields(PurchaseOrderTypeFields.AmendedOn).Value
      End Get
    End Property
    Public ReadOnly Property AdHocPayments() As Boolean
      Get
        Return mvClassFields(PurchaseOrderTypeFields.AdHocPayments).Bool
      End Get
    End Property
    Public ReadOnly Property RequiresAuthorisation() As Boolean
      Get
        Return mvClassFields(PurchaseOrderTypeFields.RequiresAuthorisation).Bool
      End Get
    End Property
    Public ReadOnly Property RegularPayments() As Boolean
      Get
        Return mvClassFields(PurchaseOrderTypeFields.RegularPayments).Bool
      End Get
    End Property
    Public ReadOnly Property RequiresPoPaymentType() As Boolean
      Get
        Return mvClassFields(PurchaseOrderTypeFields.RequiresPoPaymentType).Bool
      End Get
    End Property
#End Region

  End Class
End Namespace
