<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class ImageProvider
    Inherits System.Windows.Forms.UserControl

    'UserControl overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
    Me.components = New System.ComponentModel.Container
    Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(ImageProvider))
    Me.imgToolbar16 = New System.Windows.Forms.ImageList(Me.components)
    Me.imgToolbar32 = New System.Windows.Forms.ImageList(Me.components)
    Me.SuspendLayout()
    '
    'imgToolbar16
    '
    Me.imgToolbar16.ImageStream = CType(resources.GetObject("imgToolbar16.ImageStream"), System.Windows.Forms.ImageListStreamer)
    Me.imgToolbar16.TransparentColor = System.Drawing.Color.Transparent
    Me.imgToolbar16.Images.SetKeyName(0, "")
    Me.imgToolbar16.Images.SetKeyName(1, "")
    Me.imgToolbar16.Images.SetKeyName(2, "")
    Me.imgToolbar16.Images.SetKeyName(3, "")
    Me.imgToolbar16.Images.SetKeyName(4, "")
    Me.imgToolbar16.Images.SetKeyName(5, "")
    Me.imgToolbar16.Images.SetKeyName(6, "")
    Me.imgToolbar16.Images.SetKeyName(7, "")
    Me.imgToolbar16.Images.SetKeyName(8, "")
    Me.imgToolbar16.Images.SetKeyName(9, "")
    Me.imgToolbar16.Images.SetKeyName(10, "")
    Me.imgToolbar16.Images.SetKeyName(11, "")
    Me.imgToolbar16.Images.SetKeyName(12, "")
    Me.imgToolbar16.Images.SetKeyName(13, "")
    Me.imgToolbar16.Images.SetKeyName(14, "")
    Me.imgToolbar16.Images.SetKeyName(15, "")
    Me.imgToolbar16.Images.SetKeyName(16, "")
    Me.imgToolbar16.Images.SetKeyName(17, "")
    Me.imgToolbar16.Images.SetKeyName(18, "")
    Me.imgToolbar16.Images.SetKeyName(19, "")
    Me.imgToolbar16.Images.SetKeyName(20, "")
    Me.imgToolbar16.Images.SetKeyName(21, "")
    Me.imgToolbar16.Images.SetKeyName(22, "")
    Me.imgToolbar16.Images.SetKeyName(23, "")
    Me.imgToolbar16.Images.SetKeyName(24, "")
    Me.imgToolbar16.Images.SetKeyName(25, "")
    Me.imgToolbar16.Images.SetKeyName(26, "")
    Me.imgToolbar16.Images.SetKeyName(27, "")
    Me.imgToolbar16.Images.SetKeyName(28, "")
    Me.imgToolbar16.Images.SetKeyName(29, "")
    Me.imgToolbar16.Images.SetKeyName(30, "")
    Me.imgToolbar16.Images.SetKeyName(31, "")
    Me.imgToolbar16.Images.SetKeyName(32, "")
    Me.imgToolbar16.Images.SetKeyName(33, "")
    Me.imgToolbar16.Images.SetKeyName(34, "")
    Me.imgToolbar16.Images.SetKeyName(35, "")
    Me.imgToolbar16.Images.SetKeyName(36, "")
    Me.imgToolbar16.Images.SetKeyName(37, "")
    Me.imgToolbar16.Images.SetKeyName(38, "")
    Me.imgToolbar16.Images.SetKeyName(39, "")
    Me.imgToolbar16.Images.SetKeyName(40, "")
    Me.imgToolbar16.Images.SetKeyName(41, "")
    Me.imgToolbar16.Images.SetKeyName(42, "")
    Me.imgToolbar16.Images.SetKeyName(43, "")
    Me.imgToolbar16.Images.SetKeyName(44, "")
    Me.imgToolbar16.Images.SetKeyName(45, "")
    Me.imgToolbar16.Images.SetKeyName(46, "")
    Me.imgToolbar16.Images.SetKeyName(47, "")
    Me.imgToolbar16.Images.SetKeyName(48, "")
    Me.imgToolbar16.Images.SetKeyName(49, "")
    Me.imgToolbar16.Images.SetKeyName(50, "")
    Me.imgToolbar16.Images.SetKeyName(51, "")
    Me.imgToolbar16.Images.SetKeyName(52, "")
    Me.imgToolbar16.Images.SetKeyName(53, "")
    Me.imgToolbar16.Images.SetKeyName(54, "")
    Me.imgToolbar16.Images.SetKeyName(55, "")
    Me.imgToolbar16.Images.SetKeyName(56, "find_campaign.ico")
    Me.imgToolbar16.Images.SetKeyName(57, "separator.ico")
    Me.imgToolbar16.Images.SetKeyName(58, "businessman_add.png")
    Me.imgToolbar16.Images.SetKeyName(59, "factory_add.ico")
    Me.imgToolbar16.Images.SetKeyName(60, "clock_add.ico")
    Me.imgToolbar16.Images.SetKeyName(61, "calendar_add.ico")
    Me.imgToolbar16.Images.SetKeyName(62, "calendar_add.ico")
    Me.imgToolbar16.Images.SetKeyName(63, "calendar_add.ico")
    Me.imgToolbar16.Images.SetKeyName(64, "calendar_add.ico")
    Me.imgToolbar16.Images.SetKeyName(65, "calendar_add.ico")
    Me.imgToolbar16.Images.SetKeyName(66, "businessman_add.png")
    Me.imgToolbar16.Images.SetKeyName(67, "businessman_add.png")
    Me.imgToolbar16.Images.SetKeyName(68, "businessman_add.png")
    Me.imgToolbar16.Images.SetKeyName(69, "businessman_add.png")
    Me.imgToolbar16.Images.SetKeyName(70, "factory_add.ico")
    Me.imgToolbar16.Images.SetKeyName(71, "factory_add.ico")
    Me.imgToolbar16.Images.SetKeyName(72, "factory_add.ico")
    Me.imgToolbar16.Images.SetKeyName(73, "factory_add.ico")
    Me.imgToolbar16.Images.SetKeyName(74, "users3_find.ico")
    Me.imgToolbar16.Images.SetKeyName(75, "users3_find.ico")
    Me.imgToolbar16.Images.SetKeyName(76, "users3_find.ico")
    Me.imgToolbar16.Images.SetKeyName(77, "users3_find.ico")
    Me.imgToolbar16.Images.SetKeyName(78, "factory_find.ico")
    Me.imgToolbar16.Images.SetKeyName(79, "factory_find.ico")
    Me.imgToolbar16.Images.SetKeyName(80, "factory_find.ico")
    Me.imgToolbar16.Images.SetKeyName(81, "factory_find.ico")
    Me.imgToolbar16.Images.SetKeyName(82, "mail_server.ico")
    Me.imgToolbar16.Images.SetKeyName(83, "my_journal.ico")
    Me.imgToolbar16.Images.SetKeyName(84, "CascadeWindowsHS.png")
    Me.imgToolbar16.Images.SetKeyName(85, "ArrangeWindowsHS.png")
    Me.imgToolbar16.Images.SetKeyName(86, "ArrangeSideBySideHS.png")
    Me.imgToolbar16.Images.SetKeyName(87, "PrintSetupHS.png")
    '
    'imgToolbar32
    '
    Me.imgToolbar32.ImageStream = CType(resources.GetObject("imgToolbar32.ImageStream"), System.Windows.Forms.ImageListStreamer)
    Me.imgToolbar32.TransparentColor = System.Drawing.Color.Transparent
    Me.imgToolbar32.Images.SetKeyName(0, "")
    Me.imgToolbar32.Images.SetKeyName(1, "")
    Me.imgToolbar32.Images.SetKeyName(2, "")
    Me.imgToolbar32.Images.SetKeyName(3, "")
    Me.imgToolbar32.Images.SetKeyName(4, "")
    Me.imgToolbar32.Images.SetKeyName(5, "")
    Me.imgToolbar32.Images.SetKeyName(6, "")
    Me.imgToolbar32.Images.SetKeyName(7, "")
    Me.imgToolbar32.Images.SetKeyName(8, "")
    Me.imgToolbar32.Images.SetKeyName(9, "")
    Me.imgToolbar32.Images.SetKeyName(10, "")
    Me.imgToolbar32.Images.SetKeyName(11, "")
    Me.imgToolbar32.Images.SetKeyName(12, "")
    Me.imgToolbar32.Images.SetKeyName(13, "")
    Me.imgToolbar32.Images.SetKeyName(14, "")
    Me.imgToolbar32.Images.SetKeyName(15, "")
    Me.imgToolbar32.Images.SetKeyName(16, "")
    Me.imgToolbar32.Images.SetKeyName(17, "")
    Me.imgToolbar32.Images.SetKeyName(18, "")
    Me.imgToolbar32.Images.SetKeyName(19, "")
    Me.imgToolbar32.Images.SetKeyName(20, "")
    Me.imgToolbar32.Images.SetKeyName(21, "")
    Me.imgToolbar32.Images.SetKeyName(22, "")
    Me.imgToolbar32.Images.SetKeyName(23, "")
    Me.imgToolbar32.Images.SetKeyName(24, "")
    Me.imgToolbar32.Images.SetKeyName(25, "")
    Me.imgToolbar32.Images.SetKeyName(26, "")
    Me.imgToolbar32.Images.SetKeyName(27, "")
    Me.imgToolbar32.Images.SetKeyName(28, "")
    Me.imgToolbar32.Images.SetKeyName(29, "")
    Me.imgToolbar32.Images.SetKeyName(30, "")
    Me.imgToolbar32.Images.SetKeyName(31, "")
    Me.imgToolbar32.Images.SetKeyName(32, "")
    Me.imgToolbar32.Images.SetKeyName(33, "")
    Me.imgToolbar32.Images.SetKeyName(34, "")
    Me.imgToolbar32.Images.SetKeyName(35, "")
    Me.imgToolbar32.Images.SetKeyName(36, "")
    Me.imgToolbar32.Images.SetKeyName(37, "")
    Me.imgToolbar32.Images.SetKeyName(38, "")
    Me.imgToolbar32.Images.SetKeyName(39, "")
    Me.imgToolbar32.Images.SetKeyName(40, "")
    Me.imgToolbar32.Images.SetKeyName(41, "")
    Me.imgToolbar32.Images.SetKeyName(42, "")
    Me.imgToolbar32.Images.SetKeyName(43, "")
    Me.imgToolbar32.Images.SetKeyName(44, "")
    Me.imgToolbar32.Images.SetKeyName(45, "")
    Me.imgToolbar32.Images.SetKeyName(46, "")
    Me.imgToolbar32.Images.SetKeyName(47, "")
    Me.imgToolbar32.Images.SetKeyName(48, "")
    Me.imgToolbar32.Images.SetKeyName(49, "")
    Me.imgToolbar32.Images.SetKeyName(50, "")
    Me.imgToolbar32.Images.SetKeyName(51, "")
    Me.imgToolbar32.Images.SetKeyName(52, "")
    Me.imgToolbar32.Images.SetKeyName(53, "")
    Me.imgToolbar32.Images.SetKeyName(54, "")
    Me.imgToolbar32.Images.SetKeyName(55, "")
    Me.imgToolbar32.Images.SetKeyName(56, "find_campaign.ico")
    Me.imgToolbar32.Images.SetKeyName(57, "separator.ico")
    Me.imgToolbar32.Images.SetKeyName(58, "businessman_add.png")
    Me.imgToolbar32.Images.SetKeyName(59, "factory_add.ico")
    Me.imgToolbar32.Images.SetKeyName(60, "clock_add.ico")
    Me.imgToolbar32.Images.SetKeyName(61, "calendar_add.ico")
    Me.imgToolbar32.Images.SetKeyName(62, "calendar_add.ico")
    Me.imgToolbar32.Images.SetKeyName(63, "calendar_add.ico")
    Me.imgToolbar32.Images.SetKeyName(64, "calendar_add.ico")
    Me.imgToolbar32.Images.SetKeyName(65, "calendar_add.ico")
    Me.imgToolbar32.Images.SetKeyName(66, "businessman_add.png")
    Me.imgToolbar32.Images.SetKeyName(67, "businessman_add.png")
    Me.imgToolbar32.Images.SetKeyName(68, "businessman_add.png")
    Me.imgToolbar32.Images.SetKeyName(69, "businessman_add.png")
    Me.imgToolbar32.Images.SetKeyName(70, "factory_add.ico")
    Me.imgToolbar32.Images.SetKeyName(71, "factory_add.ico")
    Me.imgToolbar32.Images.SetKeyName(72, "factory_add.ico")
    Me.imgToolbar32.Images.SetKeyName(73, "factory_add.ico")
    Me.imgToolbar32.Images.SetKeyName(74, "users3_find.ico")
    Me.imgToolbar32.Images.SetKeyName(75, "users3_find.ico")
    Me.imgToolbar32.Images.SetKeyName(76, "users3_find.ico")
    Me.imgToolbar32.Images.SetKeyName(77, "users3_find.ico")
    Me.imgToolbar32.Images.SetKeyName(78, "factory_find.ico")
    Me.imgToolbar32.Images.SetKeyName(79, "factory_find.ico")
    Me.imgToolbar32.Images.SetKeyName(80, "factory_find.ico")
    Me.imgToolbar32.Images.SetKeyName(81, "factory_find.ico")
    Me.imgToolbar32.Images.SetKeyName(82, "mail_server.ico")
    Me.imgToolbar32.Images.SetKeyName(83, "my_journal.ico")
    '
    'ImageProvider
    '
    Me.AutoScaleDimensions = New System.Drawing.SizeF(8.0!, 16.0!)
    Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
    Me.Name = "ImageProvider"
    Me.ResumeLayout(False)

  End Sub
  Friend WithEvents imgToolbar16 As System.Windows.Forms.ImageList
  Friend WithEvents imgToolbar32 As System.Windows.Forms.ImageList

End Class
