'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

  '''<summary>
  '''BodyStart control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BodyStart As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''nfpform control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nfpform As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''ScriptManager1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

  '''<summary>
  '''MainTable control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MainTable As Global.System.Web.UI.HtmlControls.HtmlTable

  '''<summary>
  '''SiteHeader control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SiteHeader As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''phcMenu control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phcMenu As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''SiteLeftPanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SiteLeftPanel As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''CenterTable control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents CenterTable As Global.System.Web.UI.HtmlControls.HtmlTable

  '''<summary>
  '''HeadingData control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HeadingData As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''RowData control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RowData As Global.System.Web.UI.HtmlControls.HtmlTableRow

  '''<summary>
  '''LeftData control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LeftData As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''CenterData control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents CenterData As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''RightData control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RightData As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''FootingData control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FootingData As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''SiteRightPanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SiteRightPanel As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''SiteFooter control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SiteFooter As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''LastControl control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LastControl As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''BodyEnd control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BodyEnd As Global.System.Web.UI.WebControls.Literal
End Class
