Namespace Access

  Public Class PreTaxPGPaymentHistory
    Inherits CARERecord

#Region "AutoGenerated Code"

    '--------------------------------------------------
    'Enum defining all the fields in the table
    '--------------------------------------------------
    Private Enum PreTaxPGPledgePaymentHistoryFields
      AllFields = 0
      PledgeNumber
      BatchNumber
      TransactionNumber
      DonorAmount
      EmployerAmount
      GovernmentAmount
      AdminFeeAmount
      PaymentNumber
      OtherMatchedAmount
    End Enum

    '--------------------------------------------------
    'Required overrides for the class
    '--------------------------------------------------
    Protected Overrides Sub AddFields()
      With mvClassFields
        .Add("gaye_pledge_number", CDBField.FieldTypes.cftInteger)
        .Add("batch_number", CDBField.FieldTypes.cftInteger)
        .Add("transaction_number", CDBField.FieldTypes.cftInteger)
        .Add("donor_amount", CDBField.FieldTypes.cftNumeric)
        .Add("employer_amount", CDBField.FieldTypes.cftNumeric)
        .Add("government_amount", CDBField.FieldTypes.cftNumeric)
        .Add("admin_fee_amount", CDBField.FieldTypes.cftNumeric)
        .Add("payment_number", CDBField.FieldTypes.cftInteger)
        .Add("other_matched_amount", CDBField.FieldTypes.cftNumeric)

        .Item(PreTaxPGPledgePaymentHistoryFields.PledgeNumber).PrimaryKey = True
        .Item(PreTaxPGPledgePaymentHistoryFields.PledgeNumber).PrefixRequired = True


        .Item(PreTaxPGPledgePaymentHistoryFields.BatchNumber).PrimaryKey = True
        .Item(PreTaxPGPledgePaymentHistoryFields.BatchNumber).PrefixRequired = True


        .Item(PreTaxPGPledgePaymentHistoryFields.TransactionNumber).PrimaryKey = True
        .Item(PreTaxPGPledgePaymentHistoryFields.TransactionNumber).PrefixRequired = True

      End With
    End Sub

    Protected Overrides ReadOnly Property SupportsAmendedOnAndBy() As Boolean
      Get
        Return False
      End Get
    End Property
    Protected Overrides ReadOnly Property TableAlias() As String
      Get
        Return "gpph"
      End Get
    End Property
    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "gaye_pledge_payment_history"
      End Get
    End Property

    '--------------------------------------------------
    'Default constructor
    '--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub

    '--------------------------------------------------
    'Public property procedures
    '--------------------------------------------------
    Public ReadOnly Property PledgeNumber() As Integer
      Get
        Return mvClassFields(PreTaxPGPledgePaymentHistoryFields.PledgeNumber).IntegerValue
      End Get
    End Property
    Public ReadOnly Property BatchNumber() As Integer
      Get
        Return mvClassFields(PreTaxPGPledgePaymentHistoryFields.BatchNumber).IntegerValue
      End Get
    End Property
    Public ReadOnly Property TransactionNumber() As Integer
      Get
        Return mvClassFields(PreTaxPGPledgePaymentHistoryFields.TransactionNumber).IntegerValue
      End Get
    End Property
    Public ReadOnly Property DonorAmount() As Double
      Get
        Return mvClassFields(PreTaxPGPledgePaymentHistoryFields.DonorAmount).DoubleValue
      End Get
    End Property
    Public ReadOnly Property EmployerAmount() As Double
      Get
        Return mvClassFields(PreTaxPGPledgePaymentHistoryFields.EmployerAmount).DoubleValue
      End Get
    End Property
    Public ReadOnly Property GovernmentAmount() As Double
      Get
        Return mvClassFields(PreTaxPGPledgePaymentHistoryFields.GovernmentAmount).DoubleValue
      End Get
    End Property
    Public ReadOnly Property AdminFeeAmount() As Double
      Get
        Return mvClassFields(PreTaxPGPledgePaymentHistoryFields.AdminFeeAmount).DoubleValue
      End Get
    End Property
    Public ReadOnly Property PaymentNumber() As Integer
      Get
        Return mvClassFields(PreTaxPGPledgePaymentHistoryFields.PaymentNumber).IntegerValue
      End Get
    End Property
    Public ReadOnly Property OtherMatchedAmount() As Double
      Get
        Return mvClassFields(PreTaxPGPledgePaymentHistoryFields.OtherMatchedAmount).DoubleValue
      End Get
    End Property
#End Region

#Region "Non AutoGenerated Code"

    Public Overloads Sub Clone(ByVal pRecord As CARERecord, ByVal pParams As CDBParameters)
      'Cannot call MyBase.Clone(pRecord, pParams) as this table has more than 1 attribute for the primary key
      'This means we need to copy the existing data, call Update (to update any remaining data) then set the primary keys
      MyBase.CopyValues(pRecord)
      Update(pParams)
      'Update does not change primary key values so do those here
      If pParams.ContainsKey("BatchNumber") Then mvClassFields.Item(PreTaxPGPledgePaymentHistoryFields.BatchNumber).IntegerValue = pParams("BatchNumber").IntegerValue
      If pParams.ContainsKey("TransactionNumber") Then mvClassFields.Item(PreTaxPGPledgePaymentHistoryFields.TransactionNumber).IntegerValue = pParams("TransactionNumber").IntegerValue
      mvClassFields(PreTaxPGPledgePaymentHistoryFields.DonorAmount).DoubleValue = (DonorAmount * -1)
      mvClassFields(PreTaxPGPledgePaymentHistoryFields.EmployerAmount).DoubleValue = (EmployerAmount * -1)
      mvClassFields(PreTaxPGPledgePaymentHistoryFields.GovernmentAmount).DoubleValue = (GovernmentAmount * -1)
      mvClassFields(PreTaxPGPledgePaymentHistoryFields.OtherMatchedAmount).DoubleValue = (OtherMatchedAmount * -1)
      mvClassFields(PreTaxPGPledgePaymentHistoryFields.AdminFeeAmount).DoubleValue = (AdminFeeAmount * -1)
    End Sub

#End Region

  End Class
End Namespace
