Namespace Access

  Public Class LegacyStatus
    Inherits CARERecord

#Region "AutoGenerated Code"

'--------------------------------------------------
'Enum defining all the fields in the table
'--------------------------------------------------
    Private Enum LegacyStatusFields
      AllFields = 0
      LegacyStatus
      LegacyStatusDesc
      Activity
      ActivityValue
      Status
      MailingSuppression
      AmendedBy
      AmendedOn
    End Enum

'--------------------------------------------------
'Required overrides for the class
'--------------------------------------------------
    Protected Overrides Sub AddFields()
      With mvClassFields
        .Add("legacy_status")
        .Add("legacy_status_desc")
        .Add("activity")
        .Add("activity_value")
        .Add("status")
        .Add("mailing_suppression")

        .Item(LegacyStatusFields.LegacyStatus).PrimaryKey = True
      End With
    End Sub

    Protected Overrides ReadOnly Property SupportsAmendedOnAndBy() As Boolean
      Get
        Return True
      End Get
    End Property
    Protected Overrides ReadOnly Property TableAlias() As String
      Get
        Return "ls"
      End Get
    End Property
    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "legacy_statuses"
      End Get
    End Property

'--------------------------------------------------
'Default constructor
'--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub

'--------------------------------------------------
'Public property procedures
'--------------------------------------------------
    Public ReadOnly Property LegacyStatus() As String
      Get
        Return mvClassFields(LegacyStatusFields.LegacyStatus).Value
      End Get
    End Property
    Public ReadOnly Property LegacyStatusDesc() As String
      Get
        Return mvClassFields(LegacyStatusFields.LegacyStatusDesc).Value
      End Get
    End Property
    Public ReadOnly Property Activity() As String
      Get
        Return mvClassFields(LegacyStatusFields.Activity).Value
      End Get
    End Property
    Public ReadOnly Property ActivityValue() As String
      Get
        Return mvClassFields(LegacyStatusFields.ActivityValue).Value
      End Get
    End Property
    Public ReadOnly Property Status() As String
      Get
        Return mvClassFields(LegacyStatusFields.Status).Value
      End Get
    End Property
    Public ReadOnly Property MailingSuppression() As String
      Get
        Return mvClassFields(LegacyStatusFields.MailingSuppression).Value
      End Get
    End Property
    Public ReadOnly Property AmendedBy() As String
      Get
        Return mvClassFields(LegacyStatusFields.AmendedBy).Value
      End Get
    End Property
    Public ReadOnly Property AmendedOn() As String
      Get
        Return mvClassFields(LegacyStatusFields.AmendedOn).Value
      End Get
    End Property
#End Region

  End Class
End Namespace
