Namespace Access

  Public Class CustomFormControl
    Inherits CARERecord

#Region "AutoGenerated Code"

'--------------------------------------------------
'Enum defining all the fields in the table
'--------------------------------------------------
    Private Enum CustomFormControlFields
      AllFields = 0
      CustomForm
      TabNumber
      SequenceNumber
      ControlType
      AttributeName
      ControlTop
      ControlLeft
      ControlWidth
      ControlHeight
      ControlCaption
      DescSql
      SubForm
      DefaultValue
      TableName
      RestrictionAttributes
      AmendedBy
      AmendedOn
    End Enum

'--------------------------------------------------
'Required overrides for the class
'--------------------------------------------------
    Protected Overrides Sub AddFields()
      With mvClassFields
        .Add("custom_form", CDBField.FieldTypes.cftInteger)
        .Add("tab_number", CDBField.FieldTypes.cftInteger)
        .Add("sequence_number", CDBField.FieldTypes.cftInteger)
        .Add("control_type")
        .Add("attribute_name").PrefixRequired = True
        .Add("control_top", CDBField.FieldTypes.cftInteger)
        .Add("control_left", CDBField.FieldTypes.cftInteger)
        .Add("control_width", CDBField.FieldTypes.cftInteger)
        .Add("control_height", CDBField.FieldTypes.cftInteger)
        .Add("control_caption")
        .Add("desc_sql", CDBField.FieldTypes.cftMemo)
        .Add("sub_form", CDBField.FieldTypes.cftInteger)
        .Add("default_value")
        .Add("table_name").PrefixRequired = True
        .Add("restriction_attributes")

        .Item(CustomFormControlFields.CustomForm).PrimaryKey = True
        .Item(CustomFormControlFields.TabNumber).PrimaryKey = True
        .Item(CustomFormControlFields.SequenceNumber).PrimaryKey = True
      End With
    End Sub

    Protected Overrides ReadOnly Property SupportsAmendedOnAndBy() As Boolean
      Get
        Return True
      End Get
    End Property
    Protected Overrides ReadOnly Property TableAlias() As String
      Get
        Return "cfc"
      End Get
    End Property
    Protected Overrides ReadOnly Property DatabaseTableName() As String
      Get
        Return "custom_form_controls"
      End Get
    End Property

'--------------------------------------------------
'Default constructor
'--------------------------------------------------
    Public Sub New(ByVal pEnv As CDBEnvironment)
      MyBase.New(pEnv)
    End Sub

'--------------------------------------------------
'Public property procedures
'--------------------------------------------------
    Public ReadOnly Property CustomForm() As Integer
      Get
        Return mvClassFields(CustomFormControlFields.CustomForm).IntegerValue
      End Get
    End Property
    Public ReadOnly Property TabNumber() As Integer
      Get
        Return mvClassFields(CustomFormControlFields.TabNumber).IntegerValue
      End Get
    End Property
    Public ReadOnly Property SequenceNumber() As Integer
      Get
        Return mvClassFields(CustomFormControlFields.SequenceNumber).IntegerValue
      End Get
    End Property
    Public ReadOnly Property ControlType() As String
      Get
        Return mvClassFields(CustomFormControlFields.ControlType).Value
      End Get
    End Property
    Public ReadOnly Property AttributeName() As String
      Get
        Return mvClassFields(CustomFormControlFields.AttributeName).Value
      End Get
    End Property
    Public ReadOnly Property ControlTop() As Integer
      Get
        Return mvClassFields(CustomFormControlFields.ControlTop).IntegerValue
      End Get
    End Property
    Public ReadOnly Property ControlLeft() As Integer
      Get
        Return mvClassFields(CustomFormControlFields.ControlLeft).IntegerValue
      End Get
    End Property
    Public ReadOnly Property ControlWidth() As Integer
      Get
        Return mvClassFields(CustomFormControlFields.ControlWidth).IntegerValue
      End Get
    End Property
    Public ReadOnly Property ControlHeight() As Integer
      Get
        Return mvClassFields(CustomFormControlFields.ControlHeight).IntegerValue
      End Get
    End Property
    Public ReadOnly Property ControlCaption() As String
      Get
        Return mvClassFields(CustomFormControlFields.ControlCaption).Value
      End Get
    End Property
    Public ReadOnly Property DescSql() As String
      Get
        Return mvClassFields(CustomFormControlFields.DescSql).Value
      End Get
    End Property
    Public ReadOnly Property SubForm() As Integer
      Get
        Return mvClassFields(CustomFormControlFields.SubForm).IntegerValue
      End Get
    End Property
    Public ReadOnly Property AmendedBy() As String
      Get
        Return mvClassFields(CustomFormControlFields.AmendedBy).Value
      End Get
    End Property
    Public ReadOnly Property AmendedOn() As String
      Get
        Return mvClassFields(CustomFormControlFields.AmendedOn).Value
      End Get
    End Property
    Public ReadOnly Property DefaultValue() As String
      Get
        Return mvClassFields(CustomFormControlFields.DefaultValue).Value
      End Get
    End Property
    Public ReadOnly Property TableName() As String
      Get
        Return mvClassFields(CustomFormControlFields.TableName).Value
      End Get
    End Property
    Public ReadOnly Property RestrictionAttributes() As String
      Get
        Return mvClassFields(CustomFormControlFields.RestrictionAttributes).Value
      End Get
    End Property
#End Region

#Region "Non AutoGenerated Code"

    Private mvParameterName As String = ""
    Private mvCaptionWidth As Integer = 0
    Private mvMaintenanceAttribute As MaintenanceAttribute

    Protected Overrides Sub ClearFields()
      MyBase.ClearFields()
      mvParameterName = ""
      mvMaintenanceAttribute = Nothing
    End Sub

    Public Property ParameterName() As String
      Get
        Return mvParameterName
      End Get
      Set(ByVal value As String)
        mvParameterName = value
      End Set
    End Property

    Public ReadOnly Property CaptionWidth() As Integer
      Get
        Return mvCaptionWidth
      End Get
    End Property

    Public ReadOnly Property MaintenanceAttribute() As MaintenanceAttribute
      Get
        Return mvMaintenanceAttribute
      End Get
    End Property

    Public Overrides Sub InitFromRecordSet(ByVal pRecordSet As Data.CDBRecordSet)
      MyBase.InitFromRecordSet(pRecordSet)
      If ControlType = "vas" Then
        mvClassFields.Item(CustomFormControlFields.AttributeName).Value = "vas" & pRecordSet.Fields("sequence_number").LongValue
        mvClassFields.Item(CustomFormControlFields.ControlCaption).SetValue = ""
      End If
      mvMaintenanceAttribute = New MaintenanceAttribute(mvEnv)
      mvMaintenanceAttribute.InitForAdditionalInfo(True)
      mvMaintenanceAttribute.InitFromRecordSet(pRecordSet)
    End Sub

    Public Sub AdjustWidth(ByVal pCaptionWidth As Integer)
      If ControlCaption.Length > 0 Then
        mvCaptionWidth = pCaptionWidth
        If ControlType = "chk" OrElse ControlType = "opt" Then
          'Do not adjust
        Else
          mvClassFields(CustomFormControlFields.ControlLeft).IntegerValue = ControlLeft - pCaptionWidth
        End If
      End If
    End Sub

#End Region

  End Class
End Namespace
